#!/bin/sh

# Installs required packages on Debian and compatible systems.
# Author: Andreas Maunz

# NOTE: Your installed packages are safe and will not be updated.
# Java configuration is included in '$OT_UI_CONF'.

DIR=`pwd`

# Boot
. ./utils.sh || (echo "Utils could not be loaded, check opentox-ui.sh" 1>&2 && exit 1)
# Not logged
# Not logged
[ "`id -u`" = "0" ] && echo "This script must not be run as root" 1>&2 && exit 1
check_utils "aptitude apt-get apt-key apt-cache dpkg tee wget"

echo
echo "Base Packages:"
echo
echo "Updating index..."

cmd="$WGET -O redland_key.asc $REDLAND_APT_KEY  >/dev/null 2>&1" && run_cmd "$cmd" "Download redland apt-key"
cmd="sudo $APT_KEY add redland_key.asc >/dev/null 2>&1; rm redland_key.asc" && run_cmd "$cmd" "Adding redland apt-key"
if ! cat "/etc/apt/sources.list" | grep "$REDLAND_DEB">/dev/null 2>&1; then
  echo "deb $REDLAND_DEB ./" | sudo $TEE -a /etc/apt/sources.list >/dev/null
  echo "deb-src $REDLAND_DEB ./" | sudo $TEE -a /etc/apt/sources.list >/dev/null
fi

#Only for ist nightly test server (3)
case "`hostname`" in
"istnightly3" )
  FTP_DEB="http://ftp.de.debian.org/debian/"
  if ! cat "/etc/apt/sources.list" | grep "$FTP_DEB">/dev/null 2>&1; then
    echo "deb $FTP_DEB wheezy main" | sudo $TEE -a /etc/apt/sources.list >/dev/null
    echo "deb-src $FTP_DEB wheezy main" | sudo $TEE -a /etc/apt/sources.list >/dev/null
  fi
  sudo sed -i "s;deb http://http.debian.net/debian wheezy-updates main;#deb http://http.debian.net/debian wheezy-updates main;" /etc/apt/sources.list
  sudo sed -i "s;deb-src http://http.debian.net/debian wheezy-updates main;#deb-src http://http.debian.net/debian wheezy-updates main;" /etc/apt/sources.list;;
*) ;;
esac

sudo $APTITUDE update -y >/dev/null 2>&1
sudo $APTITUDE upgrade -y >/dev/null 2>&1

DISTRIB_INFO=$(cat /proc/version)

case "$DISTRIB_INFO" in
  *Debian*) echo "Debian found."; echo "$DIR/debian.list"; PACK_LIST="$DIR/debian.list";;
  *Ubuntu*) PACK_LIST="ubuntu.list";;
  *) PACK_LIST="debian.list";;
esac

sudo $APTITUDE update -y >/dev/null 2>&1
sudo $APT_GET install dselect
sudo dselect update
sudo $DPKG --set-selections < "$PACK_LIST"
sudo $APT_GET -y --force-yes -u dselect-upgrade

if [ ! -f $JAVA_CONF ]; then

  if [ ! -d "$OT_JAVA_HOME" ]; then
    if [ -d "$OT_JAVA_HOME-amd64" ]; then
      OT_JAVA_HOME="$OT_JAVA_HOME-amd64"
    else
      echo "Directory '$OT_JAVA_HOME' does not exist! Aborting..."
      echo "Please check if openjdk-6-jdk has been installed properly."
      echo "You may need to set the OT_JAVA_HOME variable in config.sh to the correct path on your system."
      exit 1
    fi
  fi

  echo "if echo \"\$JAVA_HOME\" | grep -v \"$OT_JAVA_HOME\">/dev/null 2>&1; then export JAVA_HOME=\"$OT_JAVA_HOME\"; fi" >> "$JAVA_CONF"
  echo "if echo \"\$PATH\" | grep -v \"$OT_JAVA_HOME\">/dev/null 2>&1; then export PATH=\"$OT_JAVA_HOME:\$PATH\"; fi" >> "$JAVA_CONF"
  echo "if ! [ -d \"\$JAVA_HOME\" ]; then echo \"\$0: '\$OT_JAVA_HOME' is not a directory!\"; fi" >> "$JAVA_CONF"

  echo "Java configuration stored in '$JAVA_CONF'."
  if ! grep "$JAVA_CONF" $OT_UI_CONF >/dev/null 2>&1; then
    echo '. '$JAVA_CONF >> $OT_UI_CONF
  fi
fi

cd "$DIR"

