#!/bin/sh

# Configuration options for OpenTox installations (sets shell variables for installation scripts)

# Linux distribution (currently only debian)
distribution=debian

# Installation type
# Options:
# gem	Installs only the opentox-ruby gem (useful, if you want to use external services with the opentox-ruby DSL)
# local   local installation
# server  inter or intranet server
type=local

# Git branch of services
# Options: master test development
# "master" is the current stable version
branch=master
