#!/bin/sh

# Configuration options for OpenTox installations (sets shell variables for installation scripts)

# Linux distribution (currently only debian)
distribution=debian

# Choose a root password for the MySQL database
# Please insert the correct password if mysql-server is already installed
mysql_root=opentox

# Installation type
# Options:
# gem	  installs only the opentox-ruby gem (useful, if you want to use external services with the opentox-ruby DSL)
# local   local installation (authentication and authorisation disabled)
# server  inter or intranet server (authentication and authorisation enabled)
install=server

# Git branch of services
# Options: master test development
# "master" is the current stable version
branch=development
