#!/bin/sh

# Configuration options for OpenTox installations (sets shell variables for installation scripts)

# Linux distribution (currently only debian)
distribution=debian

# Choose a root password for the MySQL database
# Please insert the correct password if mysql-server is already installed
mysql_root=opentox

# Services to be installed
# Options:
# gem	Installs only the opentox-ruby gem (useful, if you want to use external services with the opentox-ruby DSL)
# all	Installs all IST/ALU services (useful for local and server installations)
install=all

# Installation type
# Options:
# local   local installation
# server  inter or intranet server
#type=local
type=server

# Git branch of services
# Options: master test development
# "master" is the current stable version
branch=master
