#!/bin/sh
# Main Opentox-ruby install script
# Author: Christoph Helma, Andreas Maunz

LOG="/tmp/`basename $0`-log.txt"
touch $HOME/.bashrc
. "./utils.sh"
echo "Opentox-ruby installation."
echo "You may need to give root password for some privileged actions right now:"
cmd="sudo echo -n \"\"" && run_cmd "$cmd" "Acquire privileges"

. "./base-install.sh"
. "./ruby.sh"
. "./openbabel.sh"
. "./kernlab.sh"
. "./opentox-ruby.sh"

if [ "$install" != "gem" ]
then
    . "./nginx.sh"
    . "./redis.sh"
    . "./opentox-webservices.sh"
fi

