:base_dir: WWW_DEST

:services:
# make sure to enter a full uri (including training slash)
  opentox-compound:      "http://SERVERNAMENGINX_PORT/compound/"
  opentox-dataset:       "http://SERVERNAMENGINX_PORT/dataset/"
  opentox-algorithm:     "http://SERVERNAMENGINX_PORT/algorithm/"
  opentox-model:         "http://SERVERNAMENGINX_PORT/model/"
  opentox-task:          "http://SERVERNAMENGINX_PORT/task/"
  opentox-toxcreate:     "http://SERVERNAMENGINX_PORT/toxcreate/"
  opentox-validation:    "http://SERVERNAMENGINX_PORT/validation/"
  opentox-ontology:      "http://apps.ideaconsult.net:8080/ontology"

:json_hosts:
  - "localhost"
  - "SERVERNAME"
  - "webservices.in-silico.ch"
  - "opentox.informatik.uni-freiburg.de"

:ohm_port: OHM_PORT

# Uncomment for verbose logging
LOGGER
:logger: debug
:backtrace: true

