:base_dir: WWW_DEST

:services:
# make sure to enter a full uri (including training slash)
  opentox-compound:      "http://SERVERNAME/compound/"
  opentox-dataset:       "http://SERVERNAME/dataset/"
  opentox-algorithm:     "http://SERVERNAME/algorithm/"
  opentox-model:         "http://SERVERNAME/model/"
  opentox-task:          "http://SERVERNAME/task/"
  opentox-toxcreate:     "http://SERVERNAME/toxcreate/"
  opentox-validation:    "http://SERVERNAME/validation/"
  opentox-ontology:      "http://apps.ideaconsult.net:8080/ontology"

:json_hosts:
  - "localhost"
  - "SERVERNAME"
  - "webservices.in-silico.ch"
  - "opentox.informatik.uni-freiburg.de"

# Uncomment for verbose logging
LOGGER
:logger: debug
:backtrace: true

