#!/bin/sh
DIR=`pwd`
RAPTOR2=raptor2-2.0.8
RASQAL=rasqal-0.9.29
# Boot
. ./utils.sh || (echo "Utils could not be loaded, check opentox-ui.sh." 1>&2 && exit 1)
SELF=$(basename $0 -install)
check_log $SELF
#[ "`id -u`" = "0" ] && echo "This script must not be run as root" 1>&2 && exit 1
check_utils "wget tar make"

# Build
mkdir -p $PREFIX/tmp
cd $OT_PREFIX/tmp/
cmd="$WGET http://download.librdf.org/source/"$RAPTOR2".tar.gz" && run_cmd "$cmd" "Download $RAPTOR2"
export RAPTOR2_DIR=$OT_PREFIX/$SELF/$RAPTOR2
cmd="$TAR xvzf "$RAPTOR2".tar.gz" && run_cmd "$cmd" "Unzip $RAPTOR2" 
rm $RAPTOR2.tar.gz
cd $RAPTOR2
cmd="./configure --prefix=$RAPTOR2_DIR" && run_cmd "$cmd" "Configure"
cmd="$MAKE" && run_cmd "$cmd" "Make"
cmd="$MAKE install" && run_cmd "$cmd" "Make Install"
# Config
echo "if echo \"\$LD_LIBRARY_PATH\" | grep -v \"\$RAPTOR2_DIR/lib\">/dev/null 2>&1; then export LD_LIBRARY_PATH=\"\$RAPTOR2_DIR/lib:\$LD_LIBRARY_PATH\"; fi" >> "$RAPTOR2_CONF"
echo "$SELF configuration has been stored in '$RAPTOR2_CONF'."
if ! grep "$RAPTOR2_CONF" $OT_UI_CONF >/dev/null 2>&1; then
  echo '. '$RAPTOR2_CONF >> $OT_UI_CONF
fi
cd ..
export LD_LIBRARY_PATH=$RAPTOR2_DIR"/lib:"$LD_LIBRARY_PATH
export PATH=$RAPTOR2_DIR"/bin:"$PATH
export PKG_CONFIG_PATH=$RAPTOR2_DIR"/lib/pkgconfig:"$PKG_CONFIG_PATH

#Build
cmd="$WGET http://download.librdf.org/source/"$RASQAL".tar.gz" && run_cmd "$cmd" "Download $RASQAL"
export RASQAL_DIR=$OT_PREFIX/$SELF/$RASQAL
cmd="$TAR xvzf "$RASQAL".tar.gz" && run_cmd "$cmd" "Unzip $RASQAL"
rm $RASQAL.tar.gz
cd $RASQAL
cmd="./configure --prefix=$RASQAL_DIR" && run_cmd "$cmd" "Configure"
cmd="$MAKE" && run_cmd "$cmd" "Make"
cmd="$MAKE install" && run_cmd "$cmd" "Make Install"
# Config
echo "if echo \"\$LD_LIBRARY_PATH\" | grep -v \"\$RASQAL_DIR/lib\">/dev/null 2>&1; then export LD_LIBRARY_PATH=\"\$RASQAL_DIR/lib:\$LD_LIBRARY_PATH\"; fi" >> "$RASQAL_CONF"
echo "$RASQAL configuration has been stored in '$RASQAL_CONF'."
if ! grep "$RASQAL_CONF" $OT_UI_CONF >/dev/null 2>&1; then
  echo '. '$RASQAL_CONF >> $OT_UI_CONF
fi
cd ..

cd $DIR
