#!/bin/sh
. /etc/profile
gem update opentox-ruby
dir=`pwd`
cd /var/www/opentox
for s in *; do
  echo $s
  cd $s
  git pull
  cd -
done
cd /var/www/algorithm
rake fminer:update
kill `cat /opt/nginx/logs/nginx.pid`
/opt/nginx/sbin/nginx
cd $dir
